### ISSUE TITLE
Add a short blog post after whyr webinar

### ISSUE THREAD

**Issue by Nowosad** [geocompr/geocompr.github.io#10]

**Comment by Nowosad** [comment]
https://github.com/geocompr/geocompr.github.io/commit/32518a5b255ed1cad3624a338f23f083247359f7

**Comment by Robinlovelace** [comment]
Looking now.

**Comment by Robinlovelace** [comment]
Minor issue: 

![image](https://user-images.githubusercontent.com/1825120/80217450-9fc48080-8637-11ea-8265-feff2fd0f0a7.png)

**Comment by Nowosad** [comment]
Solutions:
1. Ask Marcin to change this option or..
2. Replace this video window with a link

**Comment by Robinlovelace** [comment]
I say 1. It's not too bad even if he says no because the placeholder for the video is better than just a link.
