### ISSUE TITLE
A blog post about our solutions setup

### ISSUE THREAD

**Issue by Nowosad** [geocompr/geocompr.github.io#17]
https://github.com/geocompr/solutions
https://geocompr.github.io/solutions/

**Comment by Nowosad** [comment]
https://github.com/geocompr/geocompr.github.io/commit/0375fc59e36514dcecfc2257ba09561cd4aa78e8

**Comment by Nowosad** [comment]
@Robinlovelace the solutions blog post draft is ready for your review and modifications -- https://github.com/geocompr/geocompr.github.io/blob/source/content/post/2022/geocompr-solutions.Rmd

**Comment by Robinlovelace** [comment]
Great work. Suggested changes committed, looking forward to seeing this go live :rocket: https://github.com/geocompr/geocompr.github.io/commit/8f62c1c27832cd11054958c746952ad826efd2f2

**Comment by Nowosad** [comment]
Thanks! I plan to publish it next week

**Comment by Nowosad** [comment]
https://geocompr.github.io/post/2022/geocompr-solutions/
