### ISSUE TITLE
New domain

### ISSUE THREAD

**Issue by Nowosad** [geocompr/geocompr.github.io#21]
geocomp.xyz 

Questions and comments:

1. What should be our main GitHub base (geocompr organization? geocompx? new geocompxyz organization?
2. What should be on our main webpage? Are we still keeping the blogdown page (https://geocompr.github.io/) after updating it a bit?
3. Will we be using subdomains (e.g., r.geocomp.xyz) or subdirectories (e.g., geocomp.xyz/r)?
4. We need to create redirection from geocompr.robinlovelace.net/ to the new webpage (this also applies to other versions of the book).
5. SWAG?

**Comment by Nowosad** [comment]
https://r.geocomp.xyz/ (https://geocompr.robinlovelace.net/ still works)

**Comment by Nowosad** [comment]
Now -- the question is -- how can we add subdirectories for translations and solutions? E.g., r.geocomp.xyz/es, r.geocomp.xyz/fr, etc.

**Comment by Nowosad** [comment]
Progress -- https://r.geocomp.xyz/solutions/

**Comment by Nowosad** [comment]
https://r.geocomp.xyz/fr and https://r.geocomp.xyz/es

**Comment by Robinlovelace** [comment]
Looking good!

**Comment by Robinlovelace** [comment]
Next thing that comes to mind: the organisation name. We have https://github.com/geocompx

**Comment by Robinlovelace** [comment]
And still open to other ideas. I like geocompx as a starting point, as in geocomp x (crossover) with various languages / approaches. Probably one to chat about and have messaged you on Discord @Nowosad

**Comment by Nowosad** [comment]
Related https://github.com/geocompr/geocompr.github.io/discussions/23

**Comment by Robinlovelace** [comment]
Next step I guess: replace geocompr links with geocompx links and then move and rename this repo. At some point in January I'm thinking...

**Comment by Nowosad** [comment]
1. New version of the website is ready at the quarto branch (https://github.com/geocompr/geocompr.github.io/tree/quarto). It still can be improved, but I think it is already quite solid.
2. Which links do you want to replace? I already replaced a lot of links, but, for sure, not all of them.
3. I've been thinking about the move. One possible approach is to move (and rename) this repo into our new org. However, we should also keep a small page here with a redirection to the new one.

**Comment by Nowosad** [comment]
https://geocompx.org/
