### ISSUE TITLE
Add blog post on installing R-spatial on Linux

### ISSUE THREAD

**Issue by Robinlovelace** [geocompr/geocompr.github.io#5]
Heads-up @Nowosad I'll likely request a review from you, by Friday is the aim.

**Comment by Nowosad** [comment]
@Nowosad - think about fedora edition...
https://copr.fedorainfracloud.org/coprs/iucar/cran/

**Comment by Robinlovelace** [comment]
Ubuntu, Fedora, ?Docker? Good to be modular.
