### ISSUE TITLE
covid - review

### ISSUE THREAD

**Issue by Nowosad** [geocompr/geocompr.github.io#9]
@Robinlovelace some of my comments after looking and the blog post:

- [x] It would be probably good not to download world data directly in the blog post. Maybe it is better to read it from file (or similar) with some hidden code?
- [x] There are many code chunks (and their outputs) at the beginning of the blog post. Maybe some are not necessary?
- [x] Not all animations are visible in the blog post
- [x] I think the blog post needs some more text explaining the ideas and the code

Feel free to change whatever you think is necessary and publish the blog post

**Comment by Robinlovelace** [comment]
Hi @Nowosad thanks for this. The blog post was 'code only' so will add some text and simplify the code. I think regarding 1) it's OK to download data but happy to consider alternatives, what would you suggest? Wanting to avoid pushing data into the repo.

**Comment by Nowosad** [comment]
Could you use `piggyback` in this case as well? I made that point, because when rnatualearthdata server is slow, then the website build could break.

**Comment by Nowosad** [comment]
@Robinlovelace the blog post looks great. One thing - the final animation should be updated - it is different from the current code results.

**Comment by Robinlovelace** [comment]
Yes, all good. WIP.

**Comment by Robinlovelace** [comment]
Demo of simple animated map:

![covid-19-animated-map-test](https://user-images.githubusercontent.com/1825120/80081760-454df600-854b-11ea-8805-6e9494654fb3.gif)

**Comment by Robinlovelace** [comment]
![covid-19-animated-map-test](https://user-images.githubusercontent.com/1825120/80082040-ad9cd780-854b-11ea-91b3-8a5900fb76b6.gif)

**Comment by Robinlovelace** [comment]
![covid-19-animated-map-test](https://user-images.githubusercontent.com/1825120/80087377-e7bda780-8552-11ea-959f-55b154c715fa.gif)

**Comment by Robinlovelace** [comment]
![covid-19-animated-map](https://user-images.githubusercontent.com/1825120/80092918-7f26f880-855b-11ea-8017-c4ec6e382209.gif)
